const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.OWL_PLAYWRIGHT_MODULE || 'playwright');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(root + '/src/extension.ts', 'utf8');
const start = source.indexOf('return `<!DOCTYPE html>');
let html = source.slice(start + 8, source.indexOf('</html>`;', start) + 7);
const values = { styleUri: 'file://' + root + '/media/styles.css', scriptUri: 'file://' + root + '/media/main.js', owlPngUri: 'file://' + root + '/media/owl.png', helpUri: '', nonce: 'preview', 'this._webviewSessionId': 'preview', selectStyle: '', options: '<option value=".py">Python</option>', "graphOnResultClick() ? 'checked' : ''": 'checked' };
html = require('node:vm').runInNewContext('`' + html + '`', { ...values, _webviewSessionId: 'preview', graphOnResultClick: () => true, GEMINI_TRANSLATION_MODELS: ['gemini-3.8-flash'], geminiModelLabel: model => model });
html = html.replace('<head>', `<head><script>window.sent=[];window.acquireVsCodeApi=()=>({getState:()=>null,setState:()=>{},postMessage:m=>window.sent.push(m)});</script>`);
fs.writeFileSync('/tmp/owl-simple-preview.html', html);
(async () => {
 const browser = await chromium.launch({ channel: process.env.OWL_BROWSER_CHANNEL || 'chrome', headless: true });
 try {
 const page = await browser.newPage({ viewport: { width: 440, height: 1050 } });
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.goto('file:///tmp/owl-simple-preview.html');
 const send = data => page.evaluate(data => window.dispatchEvent(new MessageEvent('message', { data })), data);
 await send({ type: 'backendSettings', backend: 'ask', model: 'Shuu12121/NightOwl-CodeEmbedding-35M', dtype: 'q8' });
 assert.equal(await page.locator('#setupAndStartBtn').innerText(), 'Choose search mode');
 await page.locator('#setupAndStartBtn').click();
 assert.equal((await page.evaluate(() => window.sent.find(message => message.command === 'setupAndStart'))).command, 'setupAndStart');
 await send({ type: 'operationState', operation: null });
 await send({ type: 'backendSettings', backend: 'node-onnx', model: 'Shuu12121/NightOwl-CodeEmbedding-35M', dtype: 'q8' });
 await send({ type: 'initState', state: { scope: 'changed', resultTypeFilter: 'function_level', activeTab: 'stats' } });
 await page.locator('#settingsPanel > summary').click();
 assert.equal(await page.locator('#scopeSelect').inputValue(), 'changed');
 assert.equal(await page.locator('#setupAndStartBtn').isVisible(), false);
 assert.equal(await page.locator('[data-tab="stats"]').isVisible(), true);
 assert.equal(await page.locator('#translationPanel').isVisible(), true);
 assert.equal(await page.locator('#agentPanel').isVisible(), true);
 assert.equal(await page.locator('#backendPanel, #searchBackendSelect, #onnxSettings').count(), 0);
 await page.locator('#searchInput').fill('password verification');
 await page.locator('#searchBtn').click();
 const msg = await page.evaluate(() => window.sent.filter(m => m.command === 'search').at(-1));
 assert.equal(msg.scope, 'changed'); assert.equal(msg.agenticEnabled, false); assert.equal(msg.translateEnabled, false);
 await send({ type: 'results', folderPath: '/fixture', results: [{ file_path: '/fixture/auth.py', lineno: 1, end_lineno: 3, name: 'verify_password', function_name: 'verify_password', class_name: 'Auth', symbol_kind: 'method', code: 'def verify_password(password):\n    return check(password)', score: 0.83, similarity: 0.83 }] });
 await send({ type: 'operationState', operation: null });
 assert.equal(await page.locator('#results .result-item').count(), 1);
 assert.match(await page.locator('#results .result-title').innerText(), /Auth.verify_password/);
 assert.equal(await page.locator('#results .result-graph-btn').count(), 1);
 await page.locator('#results .result-item').click();
 assert.equal((await page.evaluate(() => window.sent.filter(m => m.command === 'jump').at(-1))).graphEligible, true);
 await page.screenshot({ path: '/tmp/owl-simple-mode.png', fullPage: true });
 await send({ type: 'backendSettings', backend: 'python', model: 'Shuu12121/NightOwl-CodeEmbedding-35M', dtype: 'q8' });
 assert.equal(await page.locator('#setupAndStartBtn').isVisible(), true);
 assert.equal(await page.locator('body').evaluate(el => el.classList.contains('simple-backend')), false);
 assert.equal(await page.locator('#scopeSelect').inputValue(), 'changed');
 assert.deepEqual(errors, []);
 console.log('Webview passed: mode switching, stale state, function/method names and result display, server controls, Gemini and MCP controls available, busy controls, jump.');
 } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
